/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_emputi_mc_miniaturengine_application_FrameApplicationManager_Companion */

#ifndef _Included_io_github_emputi_mc_miniaturengine_application_FrameApplicationManager_Companion
#define _Included_io_github_emputi_mc_miniaturengine_application_FrameApplicationManager_Companion
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_emputi_mc_miniaturengine_application_FrameApplicationManager
	 * Method:    clearConsoleWindow
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_emputi_mc_miniaturengine_application_FrameApplicationManager_clearConsoleWindow
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_emputi_mc_miniaturengine_application_FrameApplicationManager
	 * Method:    setConsoleColors
	 * Signature: (I)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_emputi_mc_miniaturengine_application_FrameApplicationManager_setConsoleColors
	(JNIEnv*, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
