#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver */

#ifndef _Included_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
#define _Included_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
	 * Method:    getPublicKey
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver_getPublicKey
	(JNIEnv*, jobject);

	/*
	 * Class:     io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
	 * Method:    obfuscate0
	 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver_obfuscate0
	(JNIEnv*, jobject, jint, jstring, jstring, jstring);

	/*
	 * Class:     io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
	 * Method:    isValidMfeFile
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver_isValidMfeFile
	(JNIEnv*, jobject, jstring);


	JNIEXPORT jboolean JNICALL Java_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver_delegateToThread
	(JNIEnv*, jlong);

	/*
	 * Class:     io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
	 * Method:    isValidMfeChecksum
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver_isValidMfeChecksum
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver
	 * Method:    initializeHeader
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_io_github_emputi_mc_miniaturengine_communication_MfeDataDeliver_initializeHeader
	(JNIEnv*, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
